version: "2.3"
services:
  emby:
    image: emby/embyserver
    container_name: embyserver
    environment:
      - UID=1000 # The UID to run emby as (default: 2)
      - GID=100 # The GID to run emby as (default 2)
      - GIDLIST=100 # A comma-separated list of additional GIDs to run emby as (default: 2)
    volumes:
      - /home/sam/Emby/config:/config # Configuration directory
      - /home/sam/Storage/ssd2/Media/Series:/mnt/share1
      - /home/sam/Storage/ssd2/Media/Movies:/mnt/share2 
      - /home/sam/Storage/ssd2/embyshare/Unsorted:/mnt/share3 
    ports:
      - 8096:8096 # HTTP port
      - 8920:8920 # HTTPS port
    restart: unless-stopped
